<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.1" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.0.7" />
  </ItemGroup>

  <!-- Generate OpenAPI Spec on Build via Lightweight CLI -->
  <Target Name="GenerateOpenApiSpec" AfterTargets="Build">
    <MakeDir Directories="../../packages/types" />
    <Exec Command="dotnet tool restore" />
    <Exec Command="dotnet nswag run nswag.json /variables:Configuration=$(Configuration)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=NSwag" />
  </Target>

</Project>
